project:
  type: website
  output-dir: docs

website:
  title: "econ-practice-julia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Practice
        menu:
          - supply_demand_elasticity/schedules_plotting.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

