---
title: "Exploring Elasticity of Demand"
format: html
---

# Preparation: Packages and Calculation

We shall create some tables as dataframes:

```{julia}
using DataFrames
```

And maybe plot some demand curves...

```{julia}
using Plots
```

Now let's create a function to calculate elasticity using the aptly-named midpoint method.

```{julia}
calc_midpoint(x, y) = (x+y)/2

function calc_elasticity(p1, p2, q1, q2)
    # Of course, while q is quantity, p does not have to be price;
    # say, for income elasticity, p would be income.
    dp = abs(p2-p1)
    dq = abs(q2-q1)
    pm = calc_midpoint(p1, p2)
    qm = calc_midpoint(q1, q2)
    (dq/qm)/(dp/pm)
end
```

Example calculation: as price rises from \$2.85 to \$3.15, quantity of milk supplied rises from 9,000 to 11,000 gallons; then the price elasticity of milk supply in this case is 10 percent. (Which is 0.1, which is inelastic.)

```{julia}
calc_elasticity(2.85, 3.15, 9000, 11000)
```

Since we are using the midpoint method, might as well... let's make a function to calculate elasticities at midpoints from supplied data (pun unintended).

```{julia}
function calc_elasticities(ps, qs)
    changes_p = [ (ps[i+1]-ps[i]) / ((ps[i]+ps[i+1])/2) for i = 1:length(ps)-1 ]
    changes_q = [ (qs[i+1]-qs[i]) / ((qs[i]+qs[i+1])/2) for i = 1:length(qs)-1 ]
    changes_q ./ changes_p
end
```

An example: a given linear demand curve

```{julia}
calc_elasticities(  [7, 6, 5, 4, 3, 2, 1, 0],
                    [0, 2, 4, 6, 8, 10, 12, 14] )
```

Another version with midpoints:

```{julia}
function calc_ms_es(ps, qs)
    diffs_p = [ ps[i+1] - ps[i] for i=1:length(ps)-1 ]
    diffs_q = [ qs[i+1] - qs[i] for i=1:length(qs)-1 ]
    midpoints_p = [ (ps[i] + ps[i+1])/2 for i=1:length(ps)-1 ]
    midpoints_q = [ (qs[i] + qs[i+1])/2 for i=1:length(qs)-1 ]
    changes_p = diffs_p ./ midpoints_p
    changes_q = diffs_q ./ midpoints_q
    es = changes_q ./ changes_p
    midpoints_p, midpoints_q, es
end
```

Let's see how it turns out:

```{julia}
test_mps, test_mqs, test_es = calc_ms_es(   [7, 6, 5, 4, 3, 2, 1, 0],
                                            [0, 2, 4, 6, 8, 10, 12, 14] )
println("Price midpoints: \n$test_mps")
println("Quantity midpoints: \n$test_mqs")
println("Elasticities: \n$test_es")
```

# Airline Demand for Business vs. Vacation

Here's the given data.

```{julia}
airline_df = DataFrame(
    price=[150, 200, 250, 300],
    business_demand=[2100, 2000, 1900, 1800],
    vacation_demand=[1000, 800, 600, 400]
)
print(airline_df)
```

First, let's see the demand curves :)

```{julia}
plot(
    airline_df.business_demand,
    airline_df.price,
    title="Airline Demand for Business"
)
```

```{julia}
plot(
    airline_df.vacation_demand,
    airline_df.price,
    title="Airline Demand for Vacation"
)
```

Together:

```{julia}
plot(
    [airline_df.business_demand, airline_df.vacation_demand],
    airline_df.price,
    label=["for Business" "for Vacation"],
    title="Airline Demand"
)
```

Now we can calculate the elasticities...

```{julia}
business_results = calc_ms_es(airline_df.price, airline_df.business_demand)
business_mps, business_mqs, business_es = business_results

business_df = DataFrame(
    price_midpoints=business_mps,
    demand_midpoints=business_mqs,
    elasticities=business_es
)
print(business_df)
```

```{julia}
vacation_results = calc_ms_es(airline_df.price, airline_df.vacation_demand)
vacation_mps, vacation_mqs, vacation_es = vacation_results

vacation_df = DataFrame(
    price_midpoints=vacation_mps,
    demand_midpoints=vacation_mqs,
    elasticities=vacation_es
)
print(vacation_df)
```

and we can plot them: (todo)

